name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  test_backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        # no reliance on external Atlas; local Mongo will be used
    env:
      MONGODB_LOCAL: "true"
      MONGODB_LOCAL_URL: mongodb://127.0.0.1:27017/bookstore_test
      JWT_SECRET: testsecret
      PORT: 5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 16 with cache
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Wait for MongoDB port to be open
        run: |
          echo "Waiting for MongoDB to be ready on port 27017..."
          for i in {1..30}; do
            if nc -z localhost 27017; then
              echo "MongoDB is listening."
              break
            fi
            echo "MongoDB not ready yet ($i/30)..."
            sleep 2
          done
          if ! nc -z localhost 27017; then
            echo "MongoDB failed to start in time." >&2
            exit 1
          fi

      - name: Start backend in background and log output
        run: |
          # start the server and redirect output to file so we can debug later
          npm start > backend.log 2>&1 &
          echo "Backend process launched, waiting for /health..."
          n=0
          until curl --silent --fail http://localhost:5000/health || [ $n -ge 30 ]; do
            n=$((n+1))
            echo "Backend not ready yet
