name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  TestAPIEndpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Inject environment variables
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "PORT=5000" >> .env

      - name: Install dependencies
        run: npm install

      - name: Start Local Dev Server
        run: nohup npm start &

      - name: Wait for server
        run: npx wait-on http://localhost:5000


      - name: Run Cypress Tests
        run: npm run test

  DeployChanges:
    runs-on: ubuntu-latest
    needs: TestAPIEndpoints
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"