name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  TestApplicationFunctionality:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repository
        uses: actions/checkout@v2
      - name: Installing Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Installing dependencies
        run: npm install
      
      - name: Installing mongodb
        run: npm install mongodb

      - name: Installing wait-on
        run:  npm install -g wait-on 

      - name: Start Local Dev Server
        run: nohup npm start &
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}

      - name: Wait for the server to start
        run: npx wait-on http://localhost:5000

      - name: Run Cypress Tests
        run: npm run test

  DeployChanges:
    runs-on: ubuntu-latest
    needs: TestApplicationFunctionality
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deployment
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"