name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  TestApplicationFunctionality:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code repository
        uses: actions/checkout@v2
      - name: Installing Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Installing dependencies
        run: npm install

      
      - name: Start Local Dev Server
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: nohup npm start &

      - name: Wait for the server to start
        run: npx wait-on http://localhost:5000

      - name: Run Cypress Tests
        run: npm run test

  DeployChanges:
    runs-on: ubuntu-latest
    needs: TestApplicationFunctionality
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deployment
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"