name: CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  
  TestAPIEndpoints:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Clone code repository
        uses: actions/checkout@v2

      - name: Installing Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"

      - name: Inject environment variables into .env
        run: |
          echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=5000"

      - name: Installing dependencies
        run: npm install

      - name: Start Local Dev Server
        run: nohup npm start &

      - name: Run Cypress Tests
        run: npm run test

  DeployChanges:
    runs-on: ubuntu-latest
    needs: TestAPIEndpoints
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deployment
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}